### ISSUE TITLE
Latest version (v5.0) removes all items from the forge:ingots/bronze tag, breaking many recipies

### ISSUE THREAD

**Issue by DaeTheDerg** [Nemo-et-Nihil/smalltetraadditions#1]
Issue as in title.
This is not a problem on any version before 5.0

**Comment by Nemo-et-Nihil** [comment]
Are you positive it's this? I have replace:false in the section that adds create:dd bronze to the tag.

**Comment by Nemo-et-Nihil** [comment]
Fixed in the new version 5.1. Apparently I can't add a tag when the mod with the item isn't present, so i just removed it and added a material specific definition.

**Comment by DaeTheDerg** [comment]
That's great, thanks!
